stages:
  - test

test-job:
  stage: test
  image: maven:latest
  script:
    - apt update && apt install -y apt-transport-https curl
    - curl -o /etc/apt/trusted.gpg.d/mariadb_release_signing_key.asc 'https://mariadb.org/mariadb_releas_signing_key.asc'
    - sh -c "echo 'deb https://mirrors.ircam.fr/pub/mariadb/repo/10.11/ubuntu jammy main' >>/etc/apt/sources.list"
    - apt-get install -y mariadb-client
    - cat src/test/resources/sql/mariadb/create_individu.sql | mariadb --user=user -ppassword --host=database -D test
    - mvn clean test

services:
  - name: mariadb:10.11.2
    alias: database
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    variables:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test
      MARIADB_USER: user
      MARIADB_PASSWORD: password
